#!/bin/bash
set -e

. /usr/share/debconf/confmodule

# Only ask on fresh install or reconfigure
if [ "$1" = "configure" ] && [ -z "$2" ] || [ "$1" = "reconfigure" ]; then
    db_input high somasave-client/github_pat     || true
    db_input high somasave-client/github_owner       || true
    db_input high somasave-client/github_repo          || true
    db_go || true
fi

exit 0