name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build .deb
        run: |
          chmod +x packaging/build.sh
          packaging/build.sh ${{ steps.version.outputs.VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: somasave-client v${{ steps.version.outputs.VERSION }}
          body_path: CHANGELOG.md
          files: build/deb/somasave-client_${{ steps.version.outputs.VERSION }}.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to apt repo
        run: |
          git clone https://x-access-token:${{ secrets.CLIENT_TOKEN }}@github.com/ciamuthama/apt.git apt-repo
          cd apt-repo
          
          # Install reprepro
          sudo apt-get install -y reprepro
          
          mkdir -p conf
          cat > conf/distributions << EOF
          Origin: Jumbostar Solutions
          Label: Jumbostar
          Codename: stable
          Architectures: amd64 i386 source
          Components: main
          Description: Jumbostar Solutions APT Repository
          SignWith: D122FBBBDA8F1760
          EOF

          cat > conf/options << EOF
          verbose
          EOF
          
          
          # Configure GPG for signing
          mkdir -p ~/.gnupg 
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "default-cache-ttl 3600" >> ~/.gnupg/gpg-agent.conf
          echo "max-cache-ttl 3600" >> ~/.gnupg/gpg-agent.conf

          # Import GPG private key
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --no-tty --batch --yes


          # Provide passphrase to gpg-agent
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --sign --output /dev/null

          # Add .deb to repo
          reprepro \
          -b . includedeb stable \
          ../build/deb/somasave-client_${{ steps.version.outputs.VERSION }}.deb
          
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Release somasave-client v${{ steps.version.outputs.VERSION }}"
          git push
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPGKEY: ${{ secrets.GPG_KEY_ID }}